# Generated by Django 3.0.3 on 2020-02-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_hash', models.CharField(max_length=64)),
                ('profiles_that_liked', models.ManyToManyField(to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Drink_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=32)),
                ('drink_hash_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Drinks')),
            ],
        ),
    ]
