version: '3.7'

services:
  web:
    build: .
    expose:
      - 8000
    env_file:
      - env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
