version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.1
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  run-task:
    docker:
      - image: 'circlci/python:3.8'
    steps:
      - aws-ecs/run-task:
          cluster: ecs-cluster
          task-definition: bartensor-runserver:6
          launch-type: EC2

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          profile-name: jwallace145
          region: AWS_REGION
          repo: bartensor-repo
      - run-task:
          requires:
            - aws-ecr/build-and-push-image
