# Generated by Django 3.0.2 on 2020-01-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
