# Generated by Django 3.0.3 on 2020-02-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0002_auto_20200122_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
