# Generated by Django 3.0.2 on 2020-02-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0005_auto_20200207_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='profiles_that_liked',
        ),
        migrations.AddField(
            model_name='drinks',
            name='drink_hash',
            field=models.CharField(default='emptydrink', max_length=64),
        ),
    ]
