# Generated by Django 3.0.2 on 2020-02-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0007_profile_to_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='drink_hash',
            field=models.CharField(default='emptydrink', max_length=64, unique=True),
        ),
    ]
