# Generated by Django 3.0.3 on 2020-03-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0008_auto_20200209_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_to_drink',
        ),
    ]
