# Generated by Django 3.0.3 on 2020-03-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0011_profile_to_disliked_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile2', to='gnt.Profile')),
                ('profile_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile1', to='gnt.Profile')),
            ],
        ),
    ]
