# Generated by Django 3.0.3 on 2020-03-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0012_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profilerequest1', to='gnt.Profile')),
                ('request_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profilerequest2', to='gnt.Profile')),
            ],
        ),
    ]
