# Generated by Django 3.0.3 on 2020-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0014_drinks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(upload_to='drink_pics'),
        ),
    ]
