# Generated by Django 3.0.3 on 2020-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0017_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
