# Generated by Django 3.0.3 on 2020-03-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0018_user_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_to_user_drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.Profile')),
                ('user_drink_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.User_drink')),
            ],
        ),
    ]
