# Generated by Django 3.0.3 on 2020-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0019_profile_to_user_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_drink',
            name='ingredients',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
