# Generated by Django 3.0.3 on 2020-03-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0020_user_drink_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_drink',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='User_drink_to_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.Ingredient')),
                ('user_drink_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.User_drink')),
            ],
        ),
    ]
