# Generated by Django 3.0.3 on 2020-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0022_ingredient_drink_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_drink_to_ingredient',
        ),
    ]
