# Generated by Django 3.0.3 on 2020-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0023_delete_user_drink_to_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='ingredient_quantity',
        ),
        migrations.RenameField(
            model_name='user_drink',
            old_name='name',
            new_name='drink_name',
        ),
        migrations.AddField(
            model_name='user_drink',
            name='description',
            field=models.CharField(default='add a description...', max_length=100),
        ),
    ]
