# Generated by Django 3.0.3 on 2020-03-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0024_auto_20200303_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_drink',
            name='profile_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gnt.Profile'),
        ),
        migrations.DeleteModel(
            name='Profile_to_user_drink',
        ),
    ]
