# Generated by Django 3.0.3 on 2020-03-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0025_auto_20200303_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='drink_name',
            new_name='user_drink_FK',
        ),
    ]
