# Generated by Django 3.0.3 on 2020-03-04 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0026_auto_20200303_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_drink',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
