# Generated by Django 3.0.3 on 2020-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0029_auto_20200304_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='insert bio here...', max_length=250),
        ),
    ]
