# Generated by Django 3.0.3 on 2020-03-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnt', '0030_auto_20200304_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='user_drink_FK',
            new_name='drink',
        ),
        migrations.RemoveField(
            model_name='user_drink',
            name='profile_FK',
        ),
        migrations.AddField(
            model_name='user_drink',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
