# Generated by Django 3.0.3 on 2020-03-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0031_auto_20200304_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.User_drink')),
            ],
        ),
    ]
