# Generated by Django 3.0.3 on 2020-03-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0032_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='step',
            new_name='instruction',
        ),
    ]
