# Generated by Django 3.0.3 on 2020-03-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0033_auto_20200304_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserDrink',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
