# Generated by Django 3.0.3 on 2020-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0035_user_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='UserDrink',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
