# Generated by Django 3.0.3 on 2020-03-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnt', '0035_auto_20200315_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkname',
            old_name='drink_FK',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='profiletodislikeddrink',
            old_name='drink_FK',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='profiletodislikeddrink',
            old_name='profile_FK',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profiletolikeddrink',
            old_name='drink_FK',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='profiletolikeddrink',
            old_name='profile_FK',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='userdrink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
