# Generated by Django 3.0.3 on 2020-03-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0036_auto_20200315_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUserDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.UserDrink')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnt.Profile')),
            ],
        ),
    ]
