# Generated by Django 3.0.3 on 2020-03-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0036_auto_20200305_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_drink',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_drink_pics'),
        ),
    ]
