# Generated by Django 3.0.3 on 2020-03-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0037_auto_20200305_2145'),
        ('gnt', '0039_auto_20200315_1805'),
    ]

    operations = [
    ]
