# Generated by Django 3.0.3 on 2020-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0041_remove_userdrink_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdrink',
            name='votes',
        ),
        migrations.AddField(
            model_name='userdrink',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
