# Generated by Django 3.0.3 on 2020-03-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0042_auto_20200315_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdrink',
            old_name='likes',
            new_name='votes',
        ),
    ]
