# Generated by Django 3.0.3 on 2020-03-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0043_auto_20200321_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeUserDrink',
        ),
    ]
