# Generated by Django 3.0.3 on 2020-04-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0046_auto_20200403_1459'),
        ('gnt', '0046_auto_20200402_1834'),
    ]

    operations = [
    ]
