# Generated by Django 3.0.3 on 2020-04-05 16:43

from django.db import migrations, models
import django.db.models.deletion
import gnt.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0047_merge_20200405_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvoteduserdrink',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='downvoteduserdrink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.Profile'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='upvoteduserdrink',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.UserDrink'),
        ),
        migrations.AlterField(
            model_name='upvoteduserdrink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.Profile'),
        ),
        migrations.AlterField(
            model_name='userdrink',
            name='name',
            field=models.CharField(max_length=32, validators=[gnt.models.validate_user_drink_name]),
        ),
    ]
