# Generated by Django 3.0.3 on 2020-04-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0048_auto_20200405_1243'),
        ('gnt', '0046_auto_20200403_1525'),
    ]

    operations = [
    ]
