# Generated by Django 3.0.3 on 2020-04-05 19:45

from django.db import migrations, models
import gnt.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0049_merge_20200405_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdrink',
            name='name',
            field=models.CharField(max_length=32, validators=[gnt.models.validate_user_drink_name]),
        ),
    ]
