# Generated by Django 3.0.3 on 2020-04-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0050_auto_20200405_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=250)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.UserDrink')),
            ],
        ),
    ]
